=== antoromani/web-v2-i18n/schemas/front/targets.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$defs": {
    "string": {
      "type": "string",
      "minLength": 1
    }
  },
  "type": "object",
  "properties": {
    "RemoveQuest": {
      "$ref": "#/$defs/string"
    },
    "RemoveQuestSimple": {
      "$ref": "#/$defs/string"
    },
    "button": {
      "type": "object",
      "properties": {
        "AddTarget": {
          "$ref": "#/$defs/string"
        },
        "Complete": {
          "$ref": "#/$defs/string"
        },
        "PayManual": {
          "$ref": "#/$defs/string"
        }
      },
      "required": [
        "AddTarget",
        "Complete",
        "PayManual"
      ]
    },
    "label": {
      "type": "object",
      "properties": {
        "Amount": {
          "$ref": "#/$defs/string"
        },
        "CreateNewAccount": {
          "$ref": "#/$defs/string"
        },
        "HowToAccumulate": {
          "$ref": "#/$defs/string"
        },
        "Interval": {
          "$ref": "#/$defs/string"
        },
        "Name": {
          "$ref": "#/$defs/string"
        },
        "NewAccountName": {
          "$ref": "#/$defs/string"
        },
        "PayAmount": {
          "$ref": "#/$defs/string"
        },
        "PayFromAccount": {
          "$ref": "#/$defs/string"
        },
        "Remain": {
          "$ref": "#/$defs/string"
        },
        "ReserveOnAccount": {
          "$ref": "#/$defs/string"
        },
        "StartPaySince": {
          "$ref": "#/$defs/string"
        },
        "TotalAmount": {
          "$ref": "#/$defs/string"
        }
      },
      "required": [
        "Amount",
        "CreateNewAccount",
        "HowToAccumulate",
        "Interval",
        "Name",
        "NewAccountName",
        "PayAmount",
        "PayFromAccount",
        "Remain",
        "ReserveOnAccount",
        "StartPaySince",
        "TotalAmount"
      ]
    },
    "state": {
      "type": "object",
      "properties": {
        "Completed": {
          "$ref": "#/$defs/string"
        },
        "Pending": {
          "$ref": "#/$defs/string"
        }
      },
      "required": [
        "Completed",
        "Pending"
      ]
    },
    "title": {
      "type": "object",
      "properties": {
        "CreateTarget": {
          "$ref": "#/$defs/string"
        },
        "OperationsHistory": {
          "$ref": "#/$defs/string"
        },
        "PayManual": {
          "$ref": "#/$defs/string"
        },
        "page": {
          "$ref": "#/$defs/string"
        }
      },
      "required": [
        "CreateTarget",
        "OperationsHistory",
        "PayManual",
        "page"
      ]
    }
  },
  "required": [
    "RemoveQuest",
    "RemoveQuestSimple",
    "button",
    "label",
    "state",
    "title"
  ]
}

=== antoromani/web-v2-i18n/locales/en/front/targets.json
{
  "button": {
    "AddTarget": "Add\ntarget",
    "Complete": "Complete",
    "PayManual": "Pay manual"
  },
  "label": {
    "Amount": "Amount",
    "CreateNewAccount": "Create new account",
    "HowToAccumulate": "How to accumulate?",
    "Interval": "Interval",
    "Name": "Name",
    "NewAccountName": "New account name",
    "PayAmount": "Pay amount",
    "PayFromAccount": "Pay from account",
    "Remain": "Remain",
    "ReserveOnAccount": "Reserve on source account",
    "StartPaySince": "Start pay since",
    "TotalAmount": "Total amount"
  },
  "RemoveQuest": "Are you sure to delete the Goal with all related transactions? It may change accounts balance.",
  "RemoveQuestSimple": "Are you sure to delete the Goal?",
  "state": {
    "Completed": "Completed",
    "Pending": "Pending"
  },
  "title": {
    "CreateTarget": "Create target",
    "OperationsHistory": "Operations history",
    "page": "Targets",
    "PayManual": "Pay manual"
  }
}

=== antoromani/web-v2-i18n/locales/ru/front/targets.json
{
  "button": {
    "AddTarget": "Добавить\nцель",
    "Complete": "Завершить",
    "PayManual": "Заплатить вручную"
  },
  "label": {
    "Amount": "Сумма",
    "CreateNewAccount": "Создать новый счёт для цели",
    "HowToAccumulate": "Как учитывать накопленное?",
    "Interval": "Периодичность",
    "Name": "Название",
    "NewAccountName": "Название счета для цели",
    "PayAmount": "Откладывать по",
    "PayFromAccount": "Откладывать со счёта",
    "Remain": "Осталось",
    "ReserveOnAccount": "Резервировать сумму на счёте",
    "StartPaySince": "Начать откладывать с",
    "TotalAmount": "Сумма"
  },
  "RemoveQuest": "Вы действительно хотите удалить выбранную Цель? Это приведёт к удалению всех связанных транзакций, что может привести к изменению остатков на счетах.",
  "RemoveQuestSimple": "Вы действительно хотите удалить выбранную Цель?",
  "state": {
    "Completed": "Выполненные",
    "Pending": "Намеченные"
  },
  "title": {
    "CreateTarget": "Создание цели",
    "OperationsHistory": "История платежей",
    "page": "Цели",
    "PayManual": "Заплатить вручную"
  }
}

=== antoromani/web-v2-i18n/locales/el/front/targets.json
{
  "button": {
    "AddTarget": "Προσθήκη\nιμή-στόχος",
    "Complete": "Ολοκληρώθηκε",
    "PayManual": "Οδηγός πληρωμής"
  },
  "label": {
    "Amount": "Ποσό",
    "CreateNewAccount": "Δημιουργία νέου λογαριασμού",
    "HowToAccumulate": "Πώς να συσσωρεύω? ",
    "Interval": "Διάστημα",
    "Name": "Όνομα",
    "NewAccountName": "Νέο όνομα λογαριασμού",
    "PayAmount": "Ποσό πληρωμής",
    "PayFromAccount": "Πληρωμή από λογαριασμό",
    "Remain": "Παραμονή",
    "ReserveOnAccount": "Αποθεματικό στον πηγαίο λογαριασμό",
    "StartPaySince": "Έναρξη πληρωμής από",
    "TotalAmount": "Συνολικό ποσό"
  },
  "RemoveQuest": "Είστε βέβαιοι ότι θέλετε να διαγράψετε το στόχο με όλες τις σχετικές συναλλαγές; Μπορεί να αλλάξει το υπόλοιπο των λογαριασμών.",
  "RemoveQuestSimple": "Είστε βέβαιοι να διαγράψετε το στόχο?",
  "state": {
    "Completed": "Ολοκληρώθηκε",
    "Pending": "Σε εκκρεμότητα"
  },
  "title": {
    "CreateTarget": "Δημιουργία προορισμού",
    "OperationsHistory": "Ιστορικό λειτουργιών ",
    "page": "Στόχοι",
    "PayManual": "Οδηγός πληρωμής"
  }
}
